### PR TITLE
Adapt to latest eio

### PR DESCRIPTION
**Pull request by TheLortex**
First commit updates eio, second adapts API changes in mirage-tcpip.

### CODE REVIEW

**Comment by TheLortex** [comment]
OCaml CI is failing because it wants to install opam-monorepo (as there is a lockfile) but there's no version available for ocaml 5.

If the lockfile is removed, I suspect ocaml-ci will try to install all the opam files that exist in the project (including the ones in the duniverse folder)

**Comment by TheLortex** [comment]
I have disabled `http_tcpip_server` as mirage-net-unix with eio doesn't have MacOS support yet, because `eio_luv` and `luv` don't provide an easy way to import an unix file descriptor, a feature needed so that `/dev/tun` could be opened and ioctl'd appropriately before giving it to the async runtime. I'm working on finding a workaround

**Comment by haesbaert** [comment]
> I have disabled `http_tcpip_server` as mirage-net-unix with eio doesn't have MacOS support yet, because `eio_luv` and `luv` don't provide an easy way to import an unix file descriptor, a feature needed so that `/dev/tun` could be opened and ioctl'd appropriately before giving it to the async runtime. I'm working on finding a workaround

Can't you do a normal open and then `Eio_unix.FD.as_socket ~sw ~close_unix:true fd`, that's what I was doing here:  https://github.com/haesbaert/rawlink/blob/master/lib/eio_rawlink.ml
My case opens a /dev/bpf which is pretty much the same semantics of /dev/tun

**Comment by TheLortex** [comment]
Infinite thanks ! This is what I needed but I couldn't find it.

**Comment by haesbaert** [comment]
> Infinite thanks ! This is what I needed but I couldn't find it.
```
|-----------------------------------------------------------------------|
|    o   \ o /  _ o         __|    \ /     |__        o _  \ o /   o    |
|   /|\    |     /\   ___\o   \o    |    o/    o/__   /\     |    /|\   |
|   / \   / \   | \  /)  |    ( \  /o\  / )    |  (\  / |   / \   / \   |
|-----------------------------------------------------------------------|
```

**Pull request merged**
